# Deploy Chainid.io Dash (dashboard.chainid.io) in a play-with-docker playground
#
# - Go to http://play-with-docker.com/?stack=https://raw.githubusercontent.com/chainid-io/chainid-dash/master/play-with-docker/docker-stack.yml
# - Login and/or Start.
# - Wait until 'Your session is ready!' and 'Close' modal.
# - Refresh (if a shell is not shown).
# - Wait until a link with text '80' is shown. It is the link to the demo.
# - Visit https://github.com/chainid-io/chainid-dash to check default credentials.
#
version: '3'
services:
  trigger:
    image: franela/dind
    command: sh -c "git clone https://github.com/chainid-io/chainid-dash/ && ./chainid-dash/chainid-dash.sh && tail -f /dev/null"
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
